---
# Self-signed issuer for KubeClaw webhook TLS
# Requires cert-manager to be installed:
#   kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.17.1/cert-manager.yaml
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: kubeclaw-selfsigned
  namespace: kubeclaw-system
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kubeclaw-webhook-cert
  namespace: kubeclaw-system
spec:
  secretName: kubeclaw-webhook-cert
  issuerRef:
    name: kubeclaw-selfsigned
    kind: Issuer
  dnsNames:
    - kubeclaw-webhook-service
    - kubeclaw-webhook-service.kubeclaw-system
    - kubeclaw-webhook-service.kubeclaw-system.svc
    - kubeclaw-webhook-service.kubeclaw-system.svc.cluster.local
  duration: 8760h   # 1 year
  renewBefore: 720h # 30 days
