---
# Self-signed issuer for Sympozium webhook TLS
# Requires cert-manager to be installed:
#   kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.17.1/cert-manager.yaml
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: sympozium-selfsigned
  namespace: sympozium-system
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sympozium-webhook-cert
  namespace: sympozium-system
spec:
  secretName: sympozium-webhook-cert
  issuerRef:
    name: sympozium-selfsigned
    kind: Issuer
  dnsNames:
    - sympozium-webhook-service
    - sympozium-webhook-service.sympozium-system
    - sympozium-webhook-service.sympozium-system.svc
    - sympozium-webhook-service.sympozium-system.svc.cluster.local
  duration: 8760h   # 1 year
  renewBefore: 720h # 30 days
