---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sympozium-controller-manager
  namespace: sympozium-system
  labels:
    app.kubernetes.io/name: sympozium
    app.kubernetes.io/component: controller
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sympozium-apiserver
  namespace: sympozium-system
  labels:
    app.kubernetes.io/name: sympozium
    app.kubernetes.io/component: apiserver
