apiVersion: apps/v1
kind: Deployment
metadata:
  name: sympozium-apiserver
  namespace: {{ include "sympozium.namespace" . }}
  labels:
    {{- include "sympozium.labels" . | nindent 4 }}
    app.kubernetes.io/component: apiserver
spec:
  replicas: {{ .Values.apiserver.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: apiserver
  template:
    metadata:
      labels:
        app.kubernetes.io/component: apiserver
    spec:
      serviceAccountName: sympozium-apiserver
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      containers:
        - name: apiserver
          image: {{ include "sympozium.apiserverImage" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --event-bus-url={{ include "sympozium.natsUrl" . }}
          {{- if .Values.apiserver.webUI.enabled }}
            - --serve-ui
          {{- end }}
          env:
          {{- if .Values.apiserver.webUI.token }}
            - name: SYMPOZIUM_UI_TOKEN
              value: {{ .Values.apiserver.webUI.token | quote }}
          {{- else }}
            - name: SYMPOZIUM_UI_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "sympozium.fullname" . }}-ui-token
                  key: token
                  optional: true
          {{- end }}
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
          resources:
            {{- toYaml .Values.apiserver.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
      {{- with .Values.apiserver.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.apiserver.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.apiserver.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: sympozium-apiserver
  namespace: {{ include "sympozium.namespace" . }}
  labels:
    {{- include "sympozium.labels" . | nindent 4 }}
    app.kubernetes.io/component: apiserver
spec:
  selector:
    app.kubernetes.io/component: apiserver
  ports:
    - port: {{ .Values.apiserver.service.port }}
      targetPort: http
      protocol: TCP
      name: http
